### PR TITLE
Add archetypeVersion option in get-started/java-binding [ECR-1882]

### PR DESCRIPTION
**Pull request by MakarovS**
Downside of this change - we're going to need to update this field each release for now.

### CODE REVIEW

**Comment by dmitry-timofeev** [comment]
> Downside of this change - we're going to need to update this field each release for now.

**Comment by dmitry-timofeev** [comment]
> Downside of this change - we're going to need to update this field each release for now.

I believe the user have to specify the version explicitly if they already have this artefact locally (that was the case when we used it).

**Comment by MakarovS** [comment]
> I believe the user have to specify the version explicitly if they already have this artefact locally (that was the case when we used it).

When I used it without explicitly specifying the version, even if I had some newer version of archetype in my local maven cache (0.1.1 or 0.1.2), remote and old one (0.1 from maven central) was prioritised and used instead of those.

**Comment by MakarovS** [comment]
@slowli could you please take a look?

**Pull request merged**
