### PR TITLE
Add cryptocurrency tutorial

### PR DESCRIPTION
**Pull request by therustmonk**

### CODE REVIEW

**Review by slowli — COMMENTED** [review]
Some preliminary comments as of dfd6fe96c6d30aeb36f4f2445e76cbc1d743652e.

**Review by stanislav-tkach — APPROVED** [review]

**Review by stanislav-tkach — APPROVED** [review]

**Review by slowli — CHANGES_REQUESTED** [review]
Some comments as of 78529a1c7e9f12476117b305de9aff6080054f2b. I'd appreciate if you didn't force-push the entire file with edits every time and instead use atomic commits. It's easier to review changes that way, and it also positively influences your GitHub ~karma~ number of contributions 🙃

**Review by slowli — COMMENTED** [review]
Comments as of 5f3ed2aa4b4cf391cb0df28a9c7e0bec90d1775f.

**Review by slowli — COMMENTED** [review]
Comments for 8bb63ca30f0f671388b35d37ad02e3ce21d6dc44.

**Review by slowli — COMMENTED** [review]
Almost good as of 21182e67bd8d494dfecc5aa112e05b89f153438d. Please fix nitpicks (should be fast), and it will be good to merge.

**Review by slowli — APPROVED** [review]
LGTM as of 9e49ffe0d52b70687d0e9ea05cd672637e5aeb7e. Could be slightly edited for language, but can be merged without it.

**Pull request merged**
