### PR TITLE
Use latest EJB version in Javadoc

### PR DESCRIPTION
**Pull request by MakarovS**
@dmitry-timofeev Do we want to do something about such links as https://github.com/exonum/exonum-java-binding/blob/v0.1/exonum-java-binding-cryptocurrency-demo/src/test/java/com/exonum/binding/cryptocurrency/ApiControllerTest.java ? Do we want to change them to latest version manually each release? Or change `v0.1` to `master`? Or just leave it be?

### CODE REVIEW

**Comment by dmitry-timofeev** [comment]
> Do we want to change them to latest version manually each release? Or change v0.1 to master? Or just leave it be?

I'd go with updating them each release, because the chance we notice when the referenced files are renamed or deleted would be higher.

**Comment by dmitry-timofeev** [comment]
Updated in the first PR.

**Comment by slowli** [comment]
Just to clarify: do I understand correctly, that the idea is to merge #233, then this PR?

**Comment by dmitry-timofeev** [comment]
> Just to clarify: do I understand correctly, that the idea is to merge #233, then this PR?

I believe they may get merged in any order for there must not be any conflicts.

**Comment by dmitry-timofeev** [comment]
Fixed the conflict, @slowli , would you merge please?

**Pull request merged**
